# AnyGrasp Model Configuration
model:
  checkpoint_path: "log/checkpoint_detection.tar"
  max_gripper_width: 0.1
  gripper_height: 0.04
  top_down_grasp: true # Set to false for side grasp
  debug: true

# Camera Intrinsics
camera:
  fx: 383.036 
  fy: 383.036
  cx: 324.66
  cy: 242.048
  scale: 0.001000

# Workspace Limits
workspace:
  xmin: -0.19
  xmax: 0.12
  ymin: 0.02
  ymax: 0.15
  zmin: 0.0
  zmax: 1.0

# Grasp Detection Settings
grasp:
  apply_object_mask: false
  dense_grasp: true
  collision_detection: true
  num_grasps: 50